version: "3"
services: 
  rabbitmq:
    image: rabbitmq:management-alpine
    tty: true
    ports:
        - "15672:15672"
        - "5672:5672"

  rank:
    build: ./microservice/rank
    tty: true
    environment: 
      - RMQ_HOST=rabbitmq
      - RANK_PORT=8001
    volumes: 
      - ./microservice/rank:/app
    command: python /app/src/main.py
    ports: 
      - "8001:8001"

  game:
    build: ./microservice/game
    tty: true
    environment: 
      - RMQ_HOST=rabbitmq
      - GAME_PORT=8000
      - MONGODB_URL=mongodb://game:game@gamedb:27017/
    volumes: 
      - ./microservice/game:/app
    command: python /app/src/main.py
    ports: 
      - "8000:8000"

  gamedb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=game
      - MONGO_INITDB_ROOT_PASSWORD=game
    ports: 
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=gamedb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=game
      - ME_CONFIG_MONGODB_ADMINPASSWORD=game